import axios from 'axios';

export default async function handler(req, res) {
  const { username, theme = 'default', lang = 'pl' } = req.query;

  if (!username) {
    return res.status(400).send('Podaj parametr ?username=TwojNick');
  }

  try {
    const githubResponse = await axios.get(`https://api.github.com/users/${username}`);
    const data = githubResponse.data;

    const name = data.name || data.login;
    const repos = data.public_repos;
    const followers = data.followers;

    // --- TŁUMACZENIA ---
    const i18n = {
        pl: {
            title: "Statystyki GitHub",
            repos: "📦 Repozytoria:",
            followers: "👥 Obserwujący:",
            footer: "Wygenerowano przez MaxPowerPL"
        },
        en: {
            title: "GitHub Stats",
            repos: "📦 Repositories:",
            followers: "👥 Followers:",
            footer: "Generated by MaxPowerPL"
        }
    };
    const txt = i18n[lang] || i18n['pl'];

    // Definicje motywów kolorystycznych
    const themes = {
        default: { bg: '#1a1b27', stroke: '#00f2ff', text: '#ffffff', secondary: '#00f2ff' },
        gruvbox: { bg: '#282828', stroke: '#ebdbb2', text: '#ebdbb2', secondary: '#fabd2f' },
        dracula: { bg: '#282a36', stroke: '#bd93f9', text: '#f8f8f2', secondary: '#50fa7b' },
        light:   { bg: '#ffffff', stroke: '#0366d6', text: '#24292e', secondary: '#0366d6' },
        radical: { bg: '#141321', stroke: '#fe428e', text: '#a9fef7', secondary: '#fe428e' },
        merko:   { bg: '#0a0c10', stroke: '#abd200', text: '#68b587', secondary: '#abd200' },
        tokyonight: { bg: '#1a1b26', stroke: '#7aa2f7', text: '#38bdae', secondary: '#7aa2f7' }
    };

    const t = themes[theme] || themes['default'];

    const svg = `
      <svg width="400" height="200" viewBox="0 0 400 200" xmlns="http://www.w3.org/2000/svg">
        <rect width="400" height="200" rx="10" fill="${t.bg}" stroke="${t.stroke}" stroke-width="2"/>

        <text x="20" y="50" font-family="Segoe UI, Helvetica, Arial" font-size="22" fill="${t.text}" font-weight="bold">
          ${name}'s ${txt.title}
        </text>

        <line x1="20" y1="70" x2="380" y2="70" stroke="${t.stroke}" stroke-width="1" opacity="0.5"/>

        <g transform="translate(20, 110)">
            <text font-family="Segoe UI, Helvetica, Arial" font-size="16" fill="${t.secondary}">📦 ${txt.repos}</text>
            <text x="150" font-family="Segoe UI, Helvetica, Arial" font-size="16" fill="${t.text}" font-weight="bold">${repos}</text>
        </g>

        <g transform="translate(20, 150)">
            <text font-family="Segoe UI, Helvetica, Arial" font-size="16" fill="${t.secondary}">👥 ${txt.followers}</text>
            <text x="150" font-family="Segoe UI, Helvetica, Arial" font-size="16" fill="${t.text}" font-weight="bold">${followers}</text>
        </g>

        <text x="380" y="190" font-family="Segoe UI, Helvetica, Arial" font-size="10" fill="${t.text}" opacity="0.6" text-anchor="end">
          ${txt.footer}
        </text>
      </svg>
    `;

    res.setHeader('Content-Type', 'image/svg+xml');
    res.setHeader('Cache-Control', 's-maxage=60, stale-while-revalidate');
    res.status(200).send(svg);

  } catch (error) {
    res.status(500).send('Error generating stats');
  }
}