import axios from 'axios';

function calculateRank(stats) {
  const { totalStars, totalCommits, totalPRs, totalIssues, followers } = stats;

  // Wagi dla poszczególnych aktywności
  const score =
    totalCommits * 2 +
    totalPRs * 10 +
    totalIssues * 5 +
    totalStars * 20 +
    followers * 3;

  let level = '';
  let percent = 100;
  let color = '#33bbff'; // Domyślny niebieski

  // Progi punktowe (możesz dostosować)
  if (score > 15000) { level = 'S+'; percent = 100; color = '#ff3333'; } // Czerwony
  else if (score > 8000) { level = 'S'; percent = 95; color = '#ff3333'; }
  else if (score > 4000) { level = 'A+'; percent = 90; color = '#33bbff'; } // Niebieski
  else if (score > 2000) { level = 'A'; percent = 80; color = '#33bbff'; }
  else if (score > 1000) { level = 'B+'; percent = 70; color = '#2ecc71'; } // Zielony
  else if (score > 500) { level = 'B'; percent = 55; color = '#2ecc71'; }
  else { level = 'C'; percent = 40; color = '#f1c40f'; } // Żółty

  // Obliczenia dla okrągłego paska postępu SVG
  const radius = 40;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (percent / 100) * circumference;

  return { level, percent, color, circumference, offset, radius };
}

export default async function handler(req, res) {
  const { username, theme = 'default', lang = 'pl' } = req.query;

  if (!username) return res.status(400).send('Brak username');

  try {
    const token = process.env.GITHUB_TOKEN;
    if (!token) return res.status(500).send('Brak GITHUB_TOKEN w Vercel');

    // 1. ZAPYTANIE GRAPHQL
    // Pobieramy wszystkie potrzebne dane w jednym strzale
    const query = `
      query($login: String!) {
        user(login: $login) {
          name
          login
          followers { totalCount }
          repositories(first: 100, ownerAffiliations: OWNER, isFork: false) {
            totalCount
            nodes { stargazers { totalCount } }
          }
          contributionsCollection {
            totalCommitContributions
            totalPullRequestContributions
            totalIssueContributions
            totalRepositoryContributions
          }
        }
      }
    `;

    const response = await axios.post(
      'https://api.github.com/graphql',
      { query, variables: { login: username } },
      { headers: { Authorization: `bearer ${token}` } }
    );

    if (response.data.errors) throw new Error('GitHub API Error');
    const user = response.data.data.user;

    // 2. PRZETWARZANIE DANYCH
    const name = user.name || user.login;
    const followers = user.followers.totalCount;
    const totalRepos = user.repositories.totalCount;

    // Sumujemy gwiazdki ze wszystkich repozytoriów
    const totalStars = user.repositories.nodes.reduce((acc, repo) => acc + repo.stargazers.totalCount, 0);

    // Dane z contributionsCollection (ostatni rok)
    const contrib = user.contributionsCollection;
    const totalCommits = contrib.totalCommitContributions;
    const totalPRs = contrib.totalPullRequestContributions;
    const totalIssues = contrib.totalIssueContributions;
    const contributedTo = contrib.totalRepositoryContributions;

    // Obliczamy rangę
    const rank = calculateRank({ totalStars, totalCommits, totalPRs, totalIssues, followers });

    // --- TŁUMACZENIA ---
    const i18n = {
      pl: {
        title: "Statystyki GitHub", colors: "Kolorów", stars: "Gwiazdek",
        commits: "Commitów", prs: "Pull Requestów", issues: "Issues",
        contribTo: "Kontrybucje do", footer: "Wygenerowano przez MaxPowerPL"
      },
      en: {
        title: "GitHub Stats", colors: "Colors used", stars: "Total Stars",
        commits: "Total Commits", prs: "Total PRs", issues: "Total Issues",
        contribTo: "Contributed to", footer: "Generated by MaxPowerPL"
      }
    };
    const txt = i18n[lang] || i18n['pl'];

    // Definicje motywów kolorystycznych
    const themes = {
        default: { bg: '#1a1b27', stroke: '#00f2ff', text: '#ffffff', secondary: '#00f2ff' },
        gruvbox: { bg: '#282828', stroke: '#ebdbb2', text: '#ebdbb2', secondary: '#fabd2f' },
        dracula: { bg: '#282a36', stroke: '#bd93f9', text: '#f8f8f2', secondary: '#50fa7b' },
        light:   { bg: '#ffffff', stroke: '#0366d6', text: '#24292e', secondary: '#0366d6' },
        radical: { bg: '#141321', stroke: '#fe428e', text: '#a9fef7', secondary: '#fe428e' },
        merko:   { bg: '#0a0c10', stroke: '#abd200', text: '#68b587', secondary: '#abd200' },
        tokyonight: { bg: '#1a1b26', stroke: '#7aa2f7', text: '#38bdae', secondary: '#7aa2f7' }
    };

    const t = themes[theme] || themes['default'];

    const svg = `
      <svg width="450" height="230" viewBox="0 0 450 230" xmlns="http://www.w3.org/2000/svg">
        <style>
          .header { font: 600 18px 'Segoe UI', Ubuntu, Sans-Serif; fill: ${t.text}; }
          .stat-label { font: 400 14px 'Segoe UI', Ubuntu, Sans-Serif; fill: ${t.secondary}; }
          .stat-value { font: 600 14px 'Segoe UI', Ubuntu, Sans-Serif; fill: ${t.text}; }
          .rank-letter { font: 800 32px 'Segoe UI', Ubuntu, Sans-Serif; fill: ${t.text}; }
          .rank-label { font: 400 12px 'Segoe UI', Ubuntu, Sans-Serif; fill: ${t.secondary}; }
          .footer { font: 400 10px 'Segoe UI', Ubuntu, Sans-Serif; fill: ${t.text}; opacity: 0.6; }

          /* Animacja okrągłego paska */
          .progress-ring-circle {
            transition: stroke-dashoffset 0.35s;
            transform: rotate(-90deg);
            transform-origin: 50% 50%;
          }
        </style>

        <rect x="1" y="1" width="448" height="228" rx="10" fill="${t.bg}" stroke="${t.stroke}" stroke-width="2"/>

        <text x="25" y="35" class="header">
          ${name} - ${txt.title}
        </text>
        <line x1="25" y1="50" x2="425" y2="50" stroke="${t.stroke}" stroke-width="1" opacity="0.3"/>

        <g transform="translate(25, 75)">
            <g transform="translate(0, 0)">
                <text class="stat-label">⭐ ${txt.stars}:</text>
                <text x="130" class="stat-value">${totalStars}</text>
            </g>
             <g transform="translate(180, 0)">
                <text class="stat-label">🔄 ${txt.commits}:</text>
                <text x="130" class="stat-value">${totalCommits}</text>
            </g>

             <g transform="translate(0, 30)">
                <text class="stat-label">🔀 ${txt.prs}:</text>
                <text x="130" class="stat-value">${totalPRs}</text>
            </g>
             <g transform="translate(180, 30)">
                <text class="stat-label">🐛 ${txt.issues}:</text>
                <text x="130" class="stat-value">${totalIssues}</text>
            </g>

             <g transform="translate(0, 60)">
                <text class="stat-label">📦 Repos:</text>
                <text x="130" class="stat-value">${totalRepos}</text>
            </g>
             <g transform="translate(180, 60)">
                <text class="stat-label">📕 ${txt.contribTo}:</text>
                <text x="130" class="stat-value">${contributedTo}</text>
            </g>

             <g transform="translate(0, 90)">
                <text class="stat-label">👥 Followers:</text>
                <text x="130" class="stat-value">${followers}</text>
            </g>
        </g>

        <g transform="translate(360, 125)">
            <circle
                stroke="${t.stroke}"
                stroke-width="6"
                fill="transparent"
                r="${rank.radius}"
                cx="0" cy="0"
                opacity="0.2"
            />
            <circle
                class="progress-ring-circle"
                stroke="${rank.color}"
                stroke-width="6"
                stroke-linecap="round"
                fill="transparent"
                r="${rank.radius}"
                cx="0" cy="0"
                stroke-dasharray="${rank.circumference} ${rank.circumference}"
                stroke-dashoffset="${rank.offset}"
            />
            <text x="0" y="10" text-anchor="middle" class="rank-letter">${rank.level}</text>
            <text x="0" y="60" text-anchor="middle" class="rank-label">Rank</text>
        </g>

        <text x="435" y="220" class="footer" text-anchor="end">
          ${txt.footer}
        </text>
      </svg>
    `;

    res.setHeader('Content-Type', 'image/svg+xml');
    res.setHeader('Cache-Control', 's-maxage=3600, stale-while-revalidate');
    res.status(200).send(svg);

  } catch (error) {
    console.error(error);
    res.status(500).send('Error generating advanced stats');
  }
}