import axios from 'axios';

export default async function handler(req, res) {
  const { username, theme = 'default' } = req.query;

  if (!username) return res.status(400).send('Brak username');

  try {
    // Pobieramy Token z Vercela (zmiennych środowiskowych)
    const token = process.env.GITHUB_TOKEN;

    if (!token) {
        return res.status(500).send('Brak konfiguracji GITHUB_TOKEN w Vercelu');
    }

    // Zapytanie GraphQL do GitHuba o historię kontrybucji
    const query = `
      query($user: String!) {
        user(login: $user) {
          createdAt
          contributionsCollection {
            contributionCalendar {
              weeks {
                contributionDays {
                  contributionCount
                  date
                }
              }
            }
          }
        }
      }
    `;

    const response = await axios.post(
      'https://api.github.com/graphql',
      { query, variables: { user: username } },
      { headers: { Authorization: `bearer ${token}` } }
    );

    if (response.data.errors) {
        throw new Error('User not found or API error');
    }

    const calendar = response.data.data.user.contributionsCollection.contributionCalendar;

    // --- ALGORYTM OBLICZANIA STREAKA ---
    let currentStreak = 0;
    let longestStreak = 0; // (Opcjonalnie można dodać do wyświetlania)

    // Spłaszczamy strukturę tygodni do jednej listy dni
    const days = calendar.weeks.flatMap(week => week.contributionDays);

    // Sortujemy od najnowszego do najstarszego
    const reversedDays = days.reverse();

    // Sprawdzamy dzisiaj i wczoraj (żeby streak nie zerował się w środku dnia)
    const today = new Date().toISOString().split('T')[0];
    const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];

    // Szukamy indeksu startowego (dzisiaj lub wczoraj)
    let startIndex = -1;
    if (reversedDays[0].date === today && reversedDays[0].contributionCount > 0) {
        startIndex = 0;
    } else if (reversedDays[0].date === today && reversedDays[0].contributionCount === 0) {
        // Jeśli dzisiaj jeszcze nic nie zrobiłeś, sprawdzamy wczoraj
        if (reversedDays.length > 1 && reversedDays[1].date === yesterday && reversedDays[1].contributionCount > 0) {
            startIndex = 1;
        }
    }

    // Liczymy streak
    if (startIndex !== -1) {
        for (let i = startIndex; i < reversedDays.length; i++) {
            if (reversedDays[i].contributionCount > 0) {
                currentStreak++;
            } else {
                break; // Przerwa w commitowaniu = koniec streaka
            }
        }
    }

    // --- GENEROWANIE SVG ---
    const themes = {
        default: { bg: '#1a1b27', stroke: '#00f2ff', text: '#ffffff', ring: '#00f2ff' },
        gruvbox: { bg: '#282828', stroke: '#ebdbb2', text: '#ebdbb2', ring: '#fabd2f' },
        dracula: { bg: '#282a36', stroke: '#bd93f9', text: '#f8f8f2', ring: '#50fa7b' },
        light:   { bg: '#ffffff', stroke: '#0366d6', text: '#24292e', ring: '#0366d6' }
    };
    const t = themes[theme] || themes['default'];

    const svg = `
      <svg width="350" height="180" viewBox="0 0 350 180" xmlns="http://www.w3.org/2000/svg">
        <rect width="350" height="180" rx="10" fill="${t.bg}" stroke="${t.stroke}" stroke-width="2"/>

        <text x="175" y="35" font-family="Segoe UI, sans-serif" font-size="18" fill="${t.text}" font-weight="bold" text-anchor="middle">
          🔥 Current Streak
        </text>

        <text x="175" y="105" font-family="Segoe UI, sans-serif" font-size="50" fill="${t.text}" font-weight="bold" text-anchor="middle">
          ${currentStreak} days
        </text>

        <text x="175" y="140" font-family="Segoe UI, sans-serif" font-size="12" fill="${t.text}" opacity="0.7" text-anchor="middle">
          ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
        </text>

        <text x="330" y="170" font-family="Segoe UI, Helvetica, Arial" font-size="10" fill="${t.text}" opacity="0.6" text-anchor="end">
          Generated by MaxPowerPL
        </text>
      </svg>
    `;

    res.setHeader('Content-Type', 'image/svg+xml');
    res.setHeader('Cache-Control', 's-maxage=60, stale-while-revalidate');
    res.status(200).send(svg);

  } catch (error) {
    console.error(error);
    res.status(500).send('Error');
  }
}