import axios from 'axios';

export default async function handler(req, res) {
  const { username, theme = 'default', lang = 'pl' } = req.query;

  if (!username) return res.status(400).send('Brak username');

  try {
    const token = process.env.GITHUB_TOKEN;

    if (!token) {
        return res.status(500).send('Brak konfiguracji GITHUB_TOKEN w Vercelu');
    }

    const query = `
      query($user: String!) {
        user(login: $user) {
          createdAt
          contributionsCollection {
            contributionCalendar {
              weeks {
                contributionDays {
                  contributionCount
                  date
                }
              }
            }
          }
        }
      }
    `;

    const response = await axios.post(
      'https://api.github.com/graphql',
      { query, variables: { user: username } },
      { headers: { Authorization: `bearer ${token}` } }
    );

    if (response.data.errors) {
        throw new Error('User not found or API error');
    }

    const calendar = response.data.data.user.contributionsCollection.contributionCalendar;

    // --- ALGORYTMY OBLICZEŃ ---

    // 1. Przygotowanie danych (lista wszystkich dni chronologicznie)
    const days = calendar.weeks.flatMap(week => week.contributionDays);

    // 2. Obliczanie Longest Streak (W ciągu ostatniego roku)
    let longestStreak = 0;
    let tempStreak = 0;

    days.forEach(day => {
        if (day.contributionCount > 0) {
            tempStreak++;
        } else {
            if (tempStreak > longestStreak) {
                longestStreak = tempStreak;
            }
            tempStreak = 0;
        }
    });
    // Sprawdzenie na wypadek, gdyby streak trwał do ostatniego dnia
    if (tempStreak > longestStreak) {
        longestStreak = tempStreak;
    }

    // 3. Obliczanie Current Streak
    let currentStreak = 0;
    const reversedDays = [...days].reverse(); // Od najnowszego do najstarszego
    const today = new Date().toISOString().split('T')[0];
    const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];

    let startIndex = -1;
    if (reversedDays[0].date === today && reversedDays[0].contributionCount > 0) {
        startIndex = 0;
    } else if (reversedDays[0].date === today && reversedDays[0].contributionCount === 0) {
        if (reversedDays.length > 1 && reversedDays[1].date === yesterday && reversedDays[1].contributionCount > 0) {
            startIndex = 1;
        }
    }

    if (startIndex !== -1) {
        for (let i = startIndex; i < reversedDays.length; i++) {
            if (reversedDays[i].contributionCount > 0) {
                currentStreak++;
            } else {
                break;
            }
        }
    }

    // --- TŁUMACZENIA ---
    const i18n = {
        pl: {
            title: "Statystyki Streak",
            current: "Aktualny",
            longest: "Najdłuższy",
            days: "dni",
            footer: "Wygenerowano przez MaxPowerPL"
        },
        en: {
            title: "Streak Stats",
            current: "Current",
            longest: "Longest",
            days: "days",
            footer: "Generated by MaxPowerPL"
        }
    };
    const txt = i18n[lang] || i18n['pl'];

    // --- MOTYWY ---
    const themes = {
        default: { bg: '#1a1b27', stroke: '#00f2ff', text: '#ffffff', secondary: '#00f2ff' },
        gruvbox: { bg: '#282828', stroke: '#ebdbb2', text: '#ebdbb2', secondary: '#fabd2f' },
        dracula: { bg: '#282a36', stroke: '#bd93f9', text: '#f8f8f2', secondary: '#50fa7b' },
        light:   { bg: '#ffffff', stroke: '#0366d6', text: '#24292e', secondary: '#0366d6' },
        radical: { bg: '#141321', stroke: '#fe428e', text: '#a9fef7', secondary: '#fe428e' },
        merko:   { bg: '#0a0c10', stroke: '#abd200', text: '#68b587', secondary: '#abd200' },
        tokyonight: { bg: '#1a1b26', stroke: '#7aa2f7', text: '#38bdae', secondary: '#7aa2f7' }
    };
    const t = themes[theme] || themes['default'];

    // --- GENEROWANIE SVG (Dwie Kolumny) ---
    const svg = `
      <svg width="350" height="200" viewBox="0 0 350 200" xmlns="http://www.w3.org/2000/svg">
        <rect width="350" height="200" rx="10" fill="${t.bg}" stroke="${t.stroke}" stroke-width="2"/>

        <text x="175" y="35" font-family="Segoe UI, sans-serif" font-size="18" fill="${t.text}" font-weight="bold" text-anchor="middle">
          ${txt.title}
        </text>

        <line x1="175" y1="60" x2="175" y2="150" stroke="${t.stroke}" stroke-width="1" opacity="0.5" stroke-dasharray="5,5"/>

        <g transform="translate(87.5, 0)">
            <text x="0" y="80" font-family="Segoe UI, sans-serif" font-size="14" fill="${t.secondary}" text-anchor="middle">
                🔥 ${txt.current}
            </text>
            <text x="0" y="115" font-family="Segoe UI, sans-serif" font-size="32" fill="${t.text}" font-weight="bold" text-anchor="middle">
                ${currentStreak}
            </text>
            <text x="0" y="135" font-family="Segoe UI, sans-serif" font-size="12" fill="${t.text}" opacity="0.7" text-anchor="middle">
                ${txt.days}
            </text>
        </g>

        <g transform="translate(262.5, 0)">
            <text x="0" y="80" font-family="Segoe UI, sans-serif" font-size="14" fill="${t.secondary}" text-anchor="middle">
                🏆 ${txt.longest}
            </text>
            <text x="0" y="115" font-family="Segoe UI, sans-serif" font-size="32" fill="${t.text}" font-weight="bold" text-anchor="middle">
                ${longestStreak}
            </text>
            <text x="0" y="135" font-family="Segoe UI, sans-serif" font-size="12" fill="${t.text}" opacity="0.7" text-anchor="middle">
                ${txt.days}
            </text>
        </g>

        <text x="175" y="165" font-family="Segoe UI, sans-serif" font-size="10" fill="${t.text}" opacity="0.5" text-anchor="middle">
          ${new Date().toLocaleDateString(lang === 'pl' ? 'pl-PL' : 'en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
        </text>

        <text x="330" y="190" font-family="Segoe UI, Helvetica, Arial" font-size="10" fill="${t.text}" opacity="0.6" text-anchor="end">
          ${txt.footer}
        </text>
      </svg>
    `;

    res.setHeader('Content-Type', 'image/svg+xml');
    res.setHeader('Cache-Control', 's-maxage=3600, stale-while-revalidate');
    res.status(200).send(svg);

  } catch (error) {
    console.error(error);
    res.status(500).send('Error');
  }
}